"use client";

import { usePathname } from "next/navigation";
import Link from "next/link";
import { LayoutDashboard, FileSpreadsheet, Settings, HelpCircle, X, Info, BookOpen, ChevronDown, Building2, Bot } from "lucide-react";
import { useState } from "react";
import { useCompany, COMPANIES } from "@/context/CompanyContext";

export default function Navigation() {
  const pathname = usePathname();

  const { selectedCompany, setSelectedCompany } = useCompany();
  const [showGlossary, setShowGlossary] = useState(false);
  const [showCompanyList, setShowCompanyList] = useState(false);

  const navItems = [
    { label: "Agent", href: "/agent", icon: <Bot size={20} /> },
    { label: "Dashboard", href: "/", icon: <LayoutDashboard size={20} /> },
    { label: "Sheet Comparison", href: "/sheets", icon: <FileSpreadsheet size={20} /> }
  ];

  const glossaryTerms = [
    { term: "Aging", definition: "The total number of days an invoice has remained unpaid since its original due date." },
    { term: "Remind", definition: "Debtors whose invoices are between 1 and 14 days past due. These require prioritized reminders." },
    { term: "Warning", definition: "High-priority accounts 14+ days overdue or subject to L1 and L2 legal/collection scripts." },
    { term: "Verification", definition: "Resolved or paid invoices in SimPRO that require a final check before closing." },
    { term: "Triage", definition: "The process of sorting debtors into categories based on risk, amount, and history to optimize collection efforts." },
    { term: "AI Context", definition: "Brief insights generated by analyzing SimPRO notes and history to give you a head-start before making a call." },
    { term: "Suggested Action", definition: "AI-recommended script or next step based on the specific debtor's historical behavior." }
  ];

  return (
    <nav style={{ background: 'var(--nav-bg)', color: 'white', display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0 2.5rem', height: '4rem', boxShadow: 'var(--shadow-sm)', position: 'sticky', top: 0, zIndex: 1000 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '2rem' }}>
        <h2 style={{ fontSize: '1.25rem', margin: 0, fontWeight: '700', letterSpacing: '-0.02em', color: 'white', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          RIDSA DEBTOR
        </h2>
        
        <div style={{ display: 'flex', gap: '0.5rem' }}>
          {navItems.map((item) => {
            const isActive = pathname === item.href;
            return (
              <Link 
                key={item.label} 
                href={item.href}
                style={{ 
                  display: 'flex', 
                  alignItems: 'center', 
                  gap: '0.5rem', 
                  padding: '0.5rem 1rem', 
                  borderRadius: '0.375rem',
                  textDecoration: 'none',
                  color: isActive ? 'white' : 'rgba(255,255,255,0.7)',
                  background: isActive ? 'rgba(255,255,255,0.1)' : 'transparent',
                  fontWeight: '500',
                  fontSize: '0.9rem',
                  transition: 'all 0.2s'
                }}
                onMouseOver={e => !isActive && (e.currentTarget.style.background = 'rgba(255,255,255,0.05)')}
                onMouseOut={e => !isActive && (e.currentTarget.style.background = 'transparent')}
              >
                {item.icon}
                {item.label}
              </Link>
            )
          })}
        </div>
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
        {/* Company Switcher */}
        <div style={{ position: 'relative' }}>
          <button 
            onClick={() => setShowCompanyList(!showCompanyList)}
            style={{ 
              background: 'rgba(255,255,255,0.1)', 
              border: '1px solid rgba(255,255,255,0.2)', 
              color: 'white', 
              borderRadius: '0.5rem', 
              padding: '0.4rem 0.75rem', 
              fontSize: '0.85rem', 
              display: 'flex', 
              alignItems: 'center', 
              gap: '0.5rem', 
              cursor: 'pointer',
              fontWeight: '600',
              minWidth: '160px',
              justifyContent: 'space-between',
              transition: 'all 0.2s'
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Building2 size={16} />
              {selectedCompany.name}
            </div>
            <ChevronDown size={14} style={{ transform: showCompanyList ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s' }} />
          </button>

          {showCompanyList && (
            <div 
              style={{ 
                position: 'absolute', 
                top: '110%', 
                left: 0, 
                width: '100%', 
                background: 'white', 
                borderRadius: '0.5rem', 
                boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)', 
                zIndex: 1100,
                overflow: 'hidden',
                border: '1px solid #e2e8f0'
              }}
            >
              {COMPANIES.map(company => (
                <button
                  key={company.id}
                  onClick={() => {
                    setSelectedCompany(company);
                    setShowCompanyList(false);
                  }}
                  style={{
                    width: '100%',
                    padding: '0.75rem 1rem',
                    textAlign: 'left',
                    background: selectedCompany.id === company.id ? '#f8fafc' : 'white',
                    border: 'none',
                    borderLeft: selectedCompany.id === company.id ? '3px solid var(--primary)' : '3px solid transparent',
                    color: selectedCompany.id === company.id ? 'var(--primary)' : '#475569',
                    fontSize: '0.85rem',
                    fontWeight: selectedCompany.id === company.id ? '700' : '500',
                    cursor: 'pointer',
                    transition: 'all 0.15s'
                  }}
                  onMouseOver={e => ! (selectedCompany.id === company.id) && (e.currentTarget.style.background = '#f1f5f9')}
                  onMouseOut={e => ! (selectedCompany.id === company.id) && (e.currentTarget.style.background = 'white')}
                >
                  {company.name}
                </button>
              ))}
            </div>
          )}
        </div>

        <button 
          onClick={() => setShowGlossary(true)}
          style={{ 
            background: 'rgba(255,255,255,0.1)', 
            border: '1px solid rgba(255,255,255,0.2)', 
            color: 'white', 
            borderRadius: '2rem', 
            padding: '0.4rem 1rem', 
            fontSize: '0.8rem', 
            display: 'flex', 
            alignItems: 'center', 
            gap: '0.5rem', 
            cursor: 'pointer',
            fontWeight: '600',
            transition: 'all 0.2s'
          }}
          onMouseOver={e => (e.currentTarget.style.background = 'rgba(255,255,255,0.2)')}
          onMouseOut={e => (e.currentTarget.style.background = 'rgba(255,255,255,0.1)')}
        >
          <HelpCircle size={16} /> Glossary
        </button>

        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', fontSize: '0.85rem', opacity: 0.8 }}>
          <span>Logged in as <strong>Marc R.</strong></span>
        </div>
      </div>

      {/* GLOSSARY MODAL */}
      {showGlossary && (
        <div 
          style={{ position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh', background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(4px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 10000 }}
          onClick={() => setShowGlossary(false)}
        >
          <div 
            style={{ background: 'white', width: '90%', maxWidth: '500px', borderRadius: '1rem', padding: '2rem', boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1)', animation: 'slideUp 0.3s ease-out' }} 
            onClick={e => e.stopPropagation()}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', borderBottom: '1px solid #f1f5f9', paddingBottom: '1rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <BookOpen size={24} color="var(--primary)" />
                <h2 style={{ margin: 0, fontSize: '1.5rem', fontWeight: '700', color: 'var(--text-primary)' }}>System Glossary</h2>
              </div>
              <button onClick={() => setShowGlossary(false)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#94a3b8' }}>
                <X size={24} />
              </button>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
              {glossaryTerms.map((item, idx) => (
                <div key={idx} style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
                  <div style={{ background: '#fef2f2', padding: '0.4rem', borderRadius: '0.5rem', marginTop: '0.2rem' }}>
                    <Info size={16} color="var(--primary)" />
                  </div>
                  <div>
                    <div style={{ fontWeight: '700', color: 'var(--text-primary)', marginBottom: '0.2rem' }}>{item.term}</div>
                    <div style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: '1.4' }}>{item.definition}</div>
                  </div>
                </div>
              ))}
            </div>

            <button 
              onClick={() => setShowGlossary(false)} 
              className="btn btn-primary" 
              style={{ width: '100%', marginTop: '2rem', padding: '0.75rem' }}
            >
              Got it, thanks!
            </button>
          </div>
        </div>
      )}
    </nav>
  );
}
